### ISSUE TITLE
ValueError: "ConversationBufferMemory" object has no field "buffer"

### ISSUE THREAD

**Issue by sajsxj** [wxj630/visual-chatgpt-zh#18]
界面可以打开了，但是上传图片或者输入text后就显示这个错误，请问如何解决呢

**Comment by sajsxj** [comment]
<img width="956" alt="image" src="https://github.com/wxj630/visual-chatgpt-zh/assets/56745682/69a6ded1-5cd0-4b71-8496-acf0930b8de7">

**Comment by sajsxj** [comment]
<img width="1091" alt="image" src="https://github.com/wxj630/visual-chatgpt-zh/assets/56745682/86f574a8-6d05-4773-83a3-97630ef71a21">

**Comment by wxj630** [comment]
注意python包的版本号要对应上
