### ISSUE TITLE
图片无法在对话框显示

### ISSUE THREAD

**Issue by lilinyuanvr** [wxj630/visual-chatgpt-zh#2]
![Picture2](https://user-images.githubusercontent.com/33511249/225257176-520d79d0-f7ce-4a3a-8dc3-be8a56a0ee5b.png)

顺利启动了服务，除了在对话框无法显示图片其他都一切正常，发现一个resize问题导致difussioninpant失败，发现已经在今天更新修复了。麻烦指导一下是哪出了问题

**Comment by lilinyuanvr** [comment]
找到问题了    
        state = state + [(f"![](/file={image_filename})*{image_filename}*", AI_prompt)]
应该改为
        state = state + [(f"![](file={image_filename})*{image_filename}*", AI_prompt)]

**Comment by lilinyuanvr** [comment]
![image](https://user-images.githubusercontent.com/33511249/225291684-dd0e124f-684e-4490-b763-0cc64d4bf008.png)

应该去掉 file前面的 /

**Comment by wxj630** [comment]
我用linux启动+chrome浏览没有出现图片不显示的问题，不知道你是不是系统的问题还是浏览器的问题
